AWSTemplateFormatVersion: "2010-09-09"

Parameters:
  ProjectName:
    Type: String
  VpcId:
    Type: AWS::EC2::VPC::Id
  PrivateSubnetIds:
    Type: List<AWS::EC2::Subnet::Id>
  VpcEndpointSecurityGroupId:
    Type: AWS::EC2::SecurityGroup::Id
  PrivateRouteTableIds:
    Type: CommaDelimitedList

Resources:

  EcrApiEndpoint:
    Type: AWS::EC2::VPCEndpoint
    Properties:
      VpcId: !Ref VpcId
      VpcEndpointType: Interface
      ServiceName: !Sub "com.amazonaws.${AWS::Region}.ecr.api"
      SubnetIds: !Ref PrivateSubnetIds
      SecurityGroupIds:
        - !Ref VpcEndpointSecurityGroupId
      PrivateDnsEnabled: true
      Tags:
        - Key: Name
          Value: !Sub "${ProjectName}-vpce-ecr-api"

  EcrDkrEndpoint:
    Type: AWS::EC2::VPCEndpoint
    Properties:
      VpcId: !Ref VpcId
      VpcEndpointType: Interface
      ServiceName: !Sub "com.amazonaws.${AWS::Region}.ecr.dkr"
      SubnetIds: !Ref PrivateSubnetIds
      SecurityGroupIds:
        - !Ref VpcEndpointSecurityGroupId
      PrivateDnsEnabled: true
      Tags:
        - Key: Name
          Value: !Sub "${ProjectName}-vpce-ecr-dkr"

  LogsEndpoint:
    Type: AWS::EC2::VPCEndpoint
    Properties:
      VpcId: !Ref VpcId
      VpcEndpointType: Interface
      ServiceName: !Sub "com.amazonaws.${AWS::Region}.logs"
      SubnetIds: !Ref PrivateSubnetIds
      SecurityGroupIds:
        - !Ref VpcEndpointSecurityGroupId
      PrivateDnsEnabled: true
      Tags:
        - Key: Name
          Value: !Sub "${ProjectName}-vpce-logs"

  StsEndpoint:
    Type: AWS::EC2::VPCEndpoint
    Properties:
      VpcId: !Ref VpcId
      VpcEndpointType: Interface
      ServiceName: !Sub "com.amazonaws.${AWS::Region}.sts"
      SubnetIds: !Ref PrivateSubnetIds
      SecurityGroupIds:
        - !Ref VpcEndpointSecurityGroupId
      PrivateDnsEnabled: true
      Tags:
        - Key: Name
          Value: !Sub "${ProjectName}-vpce-sts"

  SecretsManagerEndpoint:
    Type: AWS::EC2::VPCEndpoint
    Properties:
      VpcId: !Ref VpcId
      VpcEndpointType: Interface
      ServiceName: !Sub "com.amazonaws.${AWS::Region}.secretsmanager"
      SubnetIds: !Ref PrivateSubnetIds
      SecurityGroupIds:
        - !Ref VpcEndpointSecurityGroupId
      PrivateDnsEnabled: true
      Tags:
        - Key: Name
          Value: !Sub "${ProjectName}-vpce-secretsmanager"

  S3GatewayEndpoint:
    Type: AWS::EC2::VPCEndpoint
    Properties:
      VpcId: !Ref VpcId
      VpcEndpointType: Gateway
      ServiceName: !Sub "com.amazonaws.${AWS::Region}.s3"
      RouteTableIds: !Ref PrivateRouteTableIds
      Tags:
        - Key: Name
          Value: !Sub "${ProjectName}-vpce-s3"
