AWSTemplateFormatVersion: "2010-09-09"

Parameters:
  ProjectName:
    Type: String
  VpcId:
    Type: AWS::EC2::VPC::Id
  PrivateSubnetIds:
    Type: List<AWS::EC2::Subnet::Id>
  VpcEndpointSecurityGroupId:
    Type: AWS::EC2::SecurityGroup::Id
  PrivateRouteTableIds:
    Type: CommaDelimitedList

Resources:

#Interface : create anNetwork Interface in each private subnet with a private IP, guarded by endpoint SG
  EcrApiEndpoint:
    Type: AWS::EC2::VPCEndpoint   #2 ECS pull images from ECR without a route to the public internet
    Properties:
      VpcId: !Ref VpcId
      VpcEndpointType: Interface
      ServiceName: !Sub "com.amazonaws.${AWS::Region}.ecr.api"
      SubnetIds: !Ref PrivateSubnetIds
      SecurityGroupIds:
        - !Ref VpcEndpointSecurityGroupId
      PrivateDnsEnabled: true
      Tags:
        - Key: Name
          Value: !Sub "${ProjectName}-vpce-ecr-api"

  EcrDkrEndpoint:
    Type: AWS::EC2::VPCEndpoint
    Properties:
      VpcId: !Ref VpcId
      VpcEndpointType: Interface
      ServiceName: !Sub "com.amazonaws.${AWS::Region}.ecr.dkr"
      SubnetIds: !Ref PrivateSubnetIds
      SecurityGroupIds:
        - !Ref VpcEndpointSecurityGroupId
      PrivateDnsEnabled: true
      Tags:
        - Key: Name
          Value: !Sub "${ProjectName}-vpce-ecr-dkr"

  LogsEndpoint:
    Type: AWS::EC2::VPCEndpoint   #ship logs -> cloudWAtch privately
    Properties:
      VpcId: !Ref VpcId
      VpcEndpointType: Interface
      ServiceName: !Sub "com.amazonaws.${AWS::Region}.logs"
      SubnetIds: !Ref PrivateSubnetIds
      SecurityGroupIds:
        - !Ref VpcEndpointSecurityGroupId
      PrivateDnsEnabled: true
      Tags:
        - Key: Name
          Value: !Sub "${ProjectName}-vpce-logs"

  StsEndpoint:
    Type: AWS::EC2::VPCEndpoint  #anything in private subnet, resolve temporary AWS credentials privately
    Properties:
      VpcId: !Ref VpcId
      VpcEndpointType: Interface
      ServiceName: !Sub "com.amazonaws.${AWS::Region}.sts"
      SubnetIds: !Ref PrivateSubnetIds
      SecurityGroupIds:
        - !Ref VpcEndpointSecurityGroupId
      PrivateDnsEnabled: true
      Tags:
        - Key: Name
          Value: !Sub "${ProjectName}-vpce-sts"

  SecretsManagerEndpoint:
    Type: AWS::EC2::VPCEndpoint   #lets ECS fetch RDS-managed db, credential from Secretfs MAnager at start up, db-usenrma, password
    Properties:
      VpcId: !Ref VpcId
      VpcEndpointType: Interface
      ServiceName: !Sub "com.amazonaws.${AWS::Region}.secretsmanager"
      SubnetIds: !Ref PrivateSubnetIds
      SecurityGroupIds:
        - !Ref VpcEndpointSecurityGroupId
      PrivateDnsEnabled: true
      Tags:
        - Key: Name
          Value: !Sub "${ProjectName}-vpce-secretsmanager"

# Gateway endpoints are just a route-table entry and are free
  S3GatewayEndpoint:
    Type: AWS::EC2::VPCEndpoint   #ECR's own Imaga layers + apps' own photo uploads
    Properties:
      VpcId: !Ref VpcId
      VpcEndpointType: Gateway
      ServiceName: !Sub "com.amazonaws.${AWS::Region}.s3"
      RouteTableIds: !Ref PrivateRouteTableIds
      Tags:
        - Key: Name
          Value: !Sub "${ProjectName}-vpce-s3"
